version: '3.8'

volumes:
  mariadb_data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/mariadb
      o: bind

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    # restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

